# Generated by Django 5.0.6 on 2024-07-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_author_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='creator',
            new_name='user',
        ),
    ]
