# Generated by Django 5.0.6 on 2024-08-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_category_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='subject',
            new_name='description',
        ),
    ]
